expat/Changes
expat/configure.ac

```
--enable-xml-context [COUNT]
Retain context around the current parse point;
default is enabled and a size of 1024 bytes
--disable-xml-context   Do not retain context around the current parse point
```

configure.ac: Add --(en|dis)able-xml-context

---

expat/coverage.sh

@RMJ10, this works for me for getting `XML_CONTEXT_BYTES` covered on *and* off in a combined report. (`gcov-tool` of GCC 5+ supports merging `.gcda` files but not `.gcno` files so I turned to `lcov` [for merging](http://stackoverflow.com/a/35120225), eventually.)
This is example output:
```
[build__R_2_2_0-121-g17c0e14__unicode_false__xml_context_0]
PASSED
[build__R_2_2_0-121-g17c0e14__unicode_false__xml_context_1024]
PASSED
Merging coverage files...
Rendering HTML report...
--> coverage__R_2_2_0-121-g17c0e14/index.html
|Lines       |Functions  |Branches    
Filename           |Rate     Num|Rate    Num|Rate     Num
=========================================================
xmlparse.c         |83.0%   3351|95.7%   141|    -      0
xmlrole.c          |97.4%    499|98.1%    54|    -      0 …
```

Add script to collect and combine code coverage across different build configurations

---

expat/Changes
expat/Makefile.in
expat/configure.ac
expat/lib/xmlparse.c

Hi!
I have applied care but it's the first take and I wasn't able to test on all involved platforms, especially not Windows.
So I value your review, testing, anything!
For Windows, @catalinr, @vszakats, @tbeu, @kwaclaw I would be grateful for your help.
@EdSchouten have a minute to see if the `libbsd`/`arc4random_buf` use and integration make sense? Does CloudABI support still work?
@hannob, @RMJ10 see anything wrong here?
Many thanks in advance!
Sebastian
PS: I'm looking for help/mentoring on porting the new detection bits from Autoconf to CMake as well. If you known anyone, please send him/her my way.

Use more sources of high quality entropy (Linux, BSD, Windows)

---

expat/MANIFEST
expat/Makefile.in
expat/lib/expat.vcxproj
expat/lib/expat.vcxproj.filters
expat/lib/expat_static.vcxproj
expat/lib/expat_static.vcxproj.filters
expat/lib/expatw.vcxproj
expat/lib/expatw.vcxproj.filters
expat/lib/expatw_static.vcxproj
expat/lib/expatw_static.vcxproj.filters
expat/lib/siphash.h
expat/lib/xmlparse.c
expat/tests/runtests.c

Known limitations: uses `sizeof(long)`bytes of entropy for the key (as hashing did before), could use up to 16 bytes. I consider using more an improvement rather than a bugfix. It deserves its own pull request, let alone due to consequences to the public API when we start using more bytes.

Change hash algorithm to Siphash

---

expat/configure.ac

the old '==' sh-is-not-C issue
It doesn't matter in bash, but some other sh don't like it, so it's a portability issue

fix sh syntax in configure.ac

---

.travis.yml

Using the build matrix can help speeding up the CI since they run
simultaneously.
Closes https://github.com/libexpat/libexpat/issues/41

Travis CI: Use build matrix

---

expat/lib/siphash.h

Explicitly cast on integer downcasting to fix compiler warnings.

Fix compiler warnings on Windows 64-bit

---

expat/lib/xmlparse.c

Explicitly use `LoadLibraryA()` instead of the `LoadLibrary()` macro, which may expand to `LoadLibraryW()` depending on build configuration. This is of course non-issue for Expat's own build system, but OTOH, it impacts embedded copies and it's also arguably cleaner code to either explicitly use the ANSI functions or use string macros for arguments (`_T("ADVAPI32.DLL")`).
It's also worth nothing that Visual Studio doesn't error out on this, but products only a warning in C:
```
lib\xmlparse.c(752): warning C4133:
'function': incompatible types - from 'char [13]' to 'LPCWSTR'
```
The consequences of passing `char*` instead of `wchar_t*` to the function are of course disastrous, and warnings may be overlooked.

Fix building on win32 if _UNICODE is defined

---

expat/lib/xmlparse.c

This solution allows the build system to chose whichever mode, instead
of forcing the "ANSI" flavour of the API.

LoadLibrary() call to work correctly regardless of _UNICODE setting

---

expat/conftools/get-version.sh

Note: I didn't bother expanding the variables with curly braces because:
- the braces are not required
- the other expansions do not use braces
- the aesthetics have been improved by not mashing the version component expansions together
Additionally, I fixed three unsafe expansions of $hdr.

Fix conftools/get-version.sh per Gentoo bug 622360

---

expat/lib/siphash.h

"#if SIPHASH_MAIN" results in -Wundef warning with recent gcc/clang and
this change suppresses it.
---
Maybe this testing code should be removed completely instead? For now I just made the smallest possible change to avoid the warning.

Check for possibly undefined SIPHASH_MAIN using #ifdef

---

expat/tests/runtests.c

Aside from a memory leak fix and some magic number elimination, most of these commits are to fix fragile allocation tests.
The tests as I originally wrote them effectively have the allocation patterns of the parser baked in, in an attempt to make sure all allocation failure code paths get executed despite some allocations being cached.  This broke instantly on undefining `XML_CONTEXT_BYTES`.  The only reliable way to solve this problem is to avoid `XML_ParserReset()` and instead free and recreate the parser.  This needs to be done using the `teardown` and `setup` functions for the relevant test cases to ensure we get a correctly configured parser each time.

Update coverage tests

---

expat/tests/chardata.c

tests/chardata.c currently compiles with a warning with GCC 7.x:
```
tests/chardata.c: In function ‘CharData_CheckString’:
tests/chardata.c:91:29: warning: ‘%s’ directive writing up to 2047 bytes into a region of size between 1209 and 1228 [-Wformat-overflow=]
sprintf(buffer, "wrong number of data characters:"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests/chardata.c:92:45: note: format string is defined here
" got %d, expected %d:\n%s", count, len, storage->data);
^~
```
This is fixed by expanding the size of the buffer - alternatively, using snprintf would work.

Expand buffer size to avoid GCC 7.x warning.

---

expat/lib/xmltok.c

With an explicit cast, the C compiler does not check whether the
function's arguments are compatible and will just convert anything.
So removing the cast makes the code safer as the compiler will
complain in more cases.  The implicit cast does the correct thing.

Do not cast arguments of memcpy(3).

---

expat/lib/siphash.h
expat/lib/xmlparse.c
expat/lib/xmltok_impl.c

Some warnings appear in gcc 7+
-Wimplicit-fallthrough
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

Fix fallthrough related warnings

---

expat/CMakeLists.txt

Fixes i.e. multilib setups on linux
Follow-up to 5681911965ef

CMake: Use GNUInstallDirs for pkgconfig too

---

expat/lib/xmlparse.c

The writeRandomBytes_arc4random is not used if the arc4random_buf
is available. This caused compiler to throw warnings.
Finally this breaks a build when warnings are treated as errors.

Fix compilation for -Werror with -Wunused-function/-Wall

---

expat/lib/libexpat.def
expat/lib/libexpatw.def

Otherwise this fails with:
Cannot export @: symbol not defined

Fix syntax of Windows module definition files

---

expat/Changes
expat/doc/Makefile.am

To fix #247 
The guard in doc/Makefile.am was supposed to protect against publishing release tarballs lacking a compiled `xmlwf.1` man page without noticing.  Now it does no more than advertised.

Fix compilation for lack of docbook2x-man (fixes #247)

---

expat/lib/xmlparse.c

My impression is that function `setElementTypePrefix` extracts the XML namespace prefix from an XML name and puts it into `elementType->prefix` if it was able find a registered prefix for that namespace:
https://github.com/libexpat/libexpat/blob/7f3291057bfc499933eddeb980ba67b9fb87834e/expat/lib/xmlparse.c#L6050-L6078
Now according to this quote …
>  [4] NCName ::= Name - (Char* ':' Char*) /* An XML Name, minus the ":" */
… from [Namespaces in XML 1.0 (Third Edition)](https://www.w3.org/TR/REC-xml-names/#NT-NCName) namespace prefixes cannot contain a colon.
It also seems that colons *should* be used in XML names for namespaces only, but do not render the name malformed if used otherwise they way I read [this](https://www.w3.org/TR/2006/REC-xml-20060816/#dt-name):
> The Namespaces in XML …

xmlparse.c: Fix extraction of namespace prefix from XML name (#186)

---

expat/CMakeLists.txt

.def files are handled differently on MinGW than MSVC for the WIN32 target:
```
[ 14%] Linking C shared library libexpat.dll
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld: ../lib/libexpat.def:4: syntax error
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld:../lib/libexpat.def: file format not recognized; treating as linker script
/usr/lib/gcc/x86_64-w64-mingw32/9.1.0/../../../../x86_64-w64-mingw32/bin/ld:../lib/libexpat.def:1: syntax error
collect2: error: ld returned 1 exit status
```

Fix link step on MinGW for CMake

---

expat/qa.sh

The current QA script would probably not catch UBSAN errors, because they don't cause the program to terminate. This patch makes sure UBSAN errors cause an abort via UBSAN_OPTIONS.

Make sure UBSAN errors cause a hard abort.

---

expat/qa.sh

This adds the -fno-common compile flag to the ASAN tests.
The standard behavior of gcc and clang is to allow multiple uninitialized global variables defined in different objects without properly marking them as extern. This has the sideeffect that these are stored in a special memory area that's not tested by ASAN, thus it can lead to undetected overflows in global variables.
Setting this flag in the QA/CI script thus has two desirable effects:
1. potential buffer overflows in global variables are detected.
2. if global variables are used in multiple files and not properly marked as "extern" the code will not link.

Add -fno-common to ASAN (for global buffer overflows)

---

expat/lib/xmltok.c

Line 658 in the macro, the expression has an int result because of plane and needs a cast.
`*(*toP)++ = **(char)** ((plane >> 2) | UTF8_cval4);			\
This takes care of the following two warnings.
xmltok.c(699): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
xmltok.c(710): warning C4244: '=': conversion from 'int' to 'char', possible loss of data
There were a few other variable shadowing warnings in 2.2.7, but it looks like those were fixed in subsequent development.   The UNUSED_P fix introduced earlier does not work on VC, and there are many, many warnings (see attached [vc15_x64_log.txt](https://github.com/libexpat/libexpat/files/3507048/vc15_x64_log.txt))     I will address those in a separate PR.
Signed-off-by: David Loffredo <loffredo@steptools.com>

fix loss of data warnings with vc15 win64 and /W4

---

expat/lib/internal.h
expat/lib/xmlparse.c
expat/lib/xmlrole.c
expat/lib/xmltok.c
expat/lib/xmltok_impl.c
expat/tests/minicheck.c
expat/tests/runtests.c
expat/xmlwf/codepage.c
expat/xmlwf/xmlfile.c
expat/xmlwf/xmlwf.c

As originally written, the UNUSED_P macro only worked for GCC.   In particular, more recent VC versions also warn about unused params.    
The typical way to handle this in C (both K&R and ANSI) has been to add a (void)param; statement in the body.     In fact, commit 69746f5ab29f3c2813bf56ccd928009914d1c8c7 that introduced the GCC attribute used the (void)  approach in some of the other test programs.    These patches change just use the (void) method consistently throughout.
Signed-off-by: David Loffredo <loffredo@steptools.com>

Handle unused parameters with (void) statement rather than gcc-specific att

---

expat/Changes
expat/README.md
expat/examples/elements.c
expat/examples/outline.c
expat/lib/expat_external.h
expat/xmlwf/xmlfile.h

- Drop support for Visual Studio <=7.1/2003
- Document supported compilers in `README.md`
- Resolve internal pre-processor macro `XML_USE_MSC_EXTENSIONS` (#323)

Drop support for MSVC 2003 (related to #323)

---

expat/Changes
expat/lib/xmlparse.c
expat/tests/runtests.c

Related to #317, work in progress.
Review wanted!
CC @yuweol @RMJ10 @DerDakon

Deny internal entities closing the doctype (for #317)

---

expat/examples/elements.c

Fix a potential memory leak in elements.c by releaseing parser memory.

Fix a potential memory leak in elements.c

---

expat/tests/runtests.c

Workaround for #332
CC @bettermanzzy

runtests.c: Workaround issue with combining XML_MIN_SIZE and ASan (#332)

---

expat/configure.ac

Enable clang tool chain for automake to generate shared libexpat libraries.
Signed-off-by: Mohammed Khajapasha <mohammed.khajapasha@intel.com>

Autotools: Enable clang tool chain to generate libraries (for #312)

---

expat/lib/xmlparse.c

There exist builds which go out of their way to define _CRT_RAND_S for
everything by forcing it into the list of macros defined on the command
line to the compiler. Unfortunately, something like "-D_CRT_RAND_S"
implies _CRT_RAND_S is defined to be '1' and defining it to be empty
produces a redefinition.
Since the intention here is to ensure that _CRT_RAND_S is always defined,
only define it if it isn't already defined.

Only define _CRT_RAND_S when not already defined.

---

expat/lib/xmlparse.c

Runtime files for MinGW don't contain rand_s() declaration, even in
their latest version, so declare it ourselves to avoid the warning about
missing function declaration.

Declare rand_s() for MinGW 32 ourselves

---

expat/lib/xmlparse.c

Related:
- Pull request #356
- MinGW bug report https://osdn.net/projects/mingw/ticket/39658

Limit declaration of rand_s to mingwrt <5.3.0

---

expat/configure.ac

Add _EXPAT_TARGET package name variable for expat.pc config
file in automake.
Signed-off-by: Mohammed Khajapasha <mohammed.khajapasha@intel.com>

Autotools: Add package name variable for expat.pc config file (issue #361)

---

expat/configure-ac-style.md
expat/doc/reference.html
expat/fuzz/xml_parse_fuzzer.c
expat/fuzz/xml_parsebuffer_fuzzer.c
expat/lib/expat.h
expat/win32/MANIFEST.txt
expat/xmlwf/xmlfile.c

Found via `codespell -q 3 -S ./testdata,./expat/Changes`

Fix source comment typos

---

expat/fuzz/xml_parsebuffer_fuzzer.c

For empty fuzzer input, The call to `XML_GetBuffer` here
https://github.com/libexpat/libexpat/blob/f56a55b32c182c7e5c41f6d07b31440ff198931a/expat/fuzz/xml_parsebuffer_fuzzer.c#L56
returns a null pointer, leading to the assertion on the following line failing. 
https://github.com/libexpat/libexpat/blob/f56a55b32c182c7e5c41f6d07b31440ff198931a/expat/fuzz/xml_parsebuffer_fuzzer.c#L57
This PR fixes this issue by bailing out early if fuzzer input is empty.

parsebuffer fuzzer: Bail out on empty fuzzer input

---

expat/CMakeLists.txt

Required by https://github.com/google/oss-fuzz/pull/3041
Enables oss fuzz integration for upstream libexpat.
This PR adds a cmake option (off by default, on for ossfuzz build) that transparently works for both libfuzzer as well as afl fuzzer back ends. Prior to this PR, the hard coding of the linker flags to `-fsanitize=fuzzer` (that is only used by libfuzzer) broke the afl build.
The oss fuzz builder bot exposes an environment variable called LIB_FUZZING_ENGINE that is used in this PR to use the correct link option.

CMake: Enable oss-fuzz integration

---

expat/CMakeLists.txt

Hello,
A tiny cmake error slipped through from #366 to master which is the following
```
CMake Warning (dev) in CMakeLists.txt:
Step #3:   A logical block opening on the line
Step #3: 
Step #3:     /src/expat/expat/CMakeLists.txt:455 (if)
Step #3: 
Step #3:   closes on the line
Step #3: 
Step #3:     /src/expat/expat/CMakeLists.txt:460 (endif)
Step #3: 
Step #3:   with mis-matching arguments.
Step #3: This warning is for project developers.  Use -Wno-dev to suppress it.
```
The error was introduced because I forgot to update the argument of `endif` cmake statement after flipping the condition of the said `if` statement (to address this comment https://github.com/libexpat/libexpat/pull/366#discussion_r347652619)
This PR fixes it :)

CMake: Fix warning due to if statement with mismatching arguments

---

expat/CMakeLists.txt

This fix link static libexpat on MSVC.
If you add this definition as public all targets links expat will automatically get this flag and don't get this:
```
> libexpat.vcxproj -> ......\bin\EXPAT\bin\_deps\expat-build\Release\libexpatMD.lib
> TestEXPAT.obj : error LNK2019: nierozpoznany zewn?trzny symbol __imp__XML_ParserCreate przywo?any w funkcji _main [......\bin\EXPAT\bin\TestEXPAT.vcxproj]
> TestEXPAT.obj : error LNK2019: nierozpoznany zewn?trzny symbol __imp__XML_SetElementHandler przywo?any w funkcji _main [......\bin\EXPAT\bin\TestEXPAT.vcxproj]
> TestEXPAT.obj : error LNK2019: nierozpoznany zewn?trzny symbol __imp__XML_SetCharacterDataHandler przywo?any w funkcji _main [......\bin\EXPAT\bin\TestEXPAT.vcxproj]
> TestEXPAT.obj : error LNK2019: nierozpoznany zewn?trzny symbol …
```

Move definition XML_STATIC to public in target

---

expat/Changes
expat/lib/xmlparse.c

Fixes #390
Pointer arithmetic with NULL is undefined behavior.
This reverts c71f27573bd0205558a78792b554764f9c962179
CC @noloader

xmlparse.c: Fix undefined behavior for XML_UNICODE (fixes #390)

---

expat/Changes
expat/conftools/ax-check-compile-flag.m4

CC @noloader 
~Potential new base for pull request #387~, related to issue #383.
Before and after for Clang 9:
```diff
-checking whether C compiler accepts -Wduplicated-cond... yes
-checking whether C compiler accepts -Wduplicated-branches... yes
-checking whether C compiler accepts -Wlogical-op... yes
-checking whether C compiler accepts -Wrestrict... yes
+checking whether C compiler accepts -Wduplicated-cond... no
+checking whether C compiler accepts -Wduplicated-branches... no
+checking whether C compiler accepts -Wlogical-op... no
+checking whether C compiler accepts -Wrestrict... no
@@ -90 +90 @@
-checking whether C compiler accepts -Wjump-misses-init... yes
+checking whether C compiler accepts -Wjump-misses-init... no
@@ -94 +94 @@
-checking whether C compiler accepts …
```

conftools: Use -Werror when checking compile flags

---

expat/lib/xmlparse.c

In C it is undefined to add anything to NULL. Clang recently began
taking advantage of this and can assume that if anything is added or
subtracted from a pointer that the pointer can be assumed non-NULL. The
Address Sanitizer has been updated to report when this happens at
runtime and produces messages like
expat/lib/xmlparse.c:6509:23: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior expat/lib/xmlparse.c:6509:23
This can be mitigated with 'p ? p + n : NULL' which optimizes to just
the add in all optimizing compilers, but avoids the undefined behavior.

Don't add to NULL in iterator.

---

expat/doc/xmlwf.xml
expat/xmlwf/xmlwf.c

Since 70a4a691fc43644e69d3876ed7d43ab717c9cb43 the exit codes are useful for xmlwf, so update the man page.

Document the exit codes for xmlwf.

---

expat/lib/xmltok_impl.c

While unsigned integer overflow is well-defined, Android sanitizers treat it
as an error. We also have some in the SipHash implementation but those won't
be easy to get rid of.

Get rid of unsigned integer overflow in column calculation

---

expat/CMakeLists.txt

added "new" behaviour for Policy CMP0077 which allows to control the build options by cmake variables if lib is used by FetchContent of a super project
example usage as subproject: 
FetchContent_Declare(expat
GIT_REPOSITORY https://github.com/gittiver/libexpat.git
GIT_TAG master)
if(NOT expat_POPULATED)
set(EXPAT_SHARED_LIBS Off)
set(EXPAT_BUILD_TOOLS Off)
set(EXPAT_BUILD_EXAMPLES Off)
set(EXPAT_BUILD_TESTS Off)
set(EXPAT_SHARED_LIBS Off)
set(EXPAT_BUILD_DOCS Off)
set(EXPAT_BUILD_FUZZERS Off)
set(EXPAT_WITH_LIBBSD Off)
set(EXPAT_ENABLE_INSTALL On)
FetchContent_Populate(expat)
add_subdirectory(${expat_SOURCE_DIR}/expat ${expat_BINARY_DIR})

control build options by variables on usage by cmake FetchContent command

---

expat/CMakeLists.txt

On Linux, this will create a file `expat-2.2.9-Linux.tar.gz` with the following content:
```
$ tar tf expat-2.2.9-Linux.tar.gz | sort | grep -v '/$'
expat-2.2.9-Linux/bin/xmlwf
expat-2.2.9-Linux/include/expat_config.h
expat-2.2.9-Linux/include/expat_external.h
expat-2.2.9-Linux/include/expat.h
expat-2.2.9-Linux/lib64/cmake/expat-2.2.9/expat.cmake
expat-2.2.9-Linux/lib64/cmake/expat-2.2.9/expat-config.cmake
expat-2.2.9-Linux/lib64/cmake/expat-2.2.9/expat-config-version.cmake
expat-2.2.9-Linux/lib64/cmake/expat-2.2.9/expat-noconfig.cmake
expat-2.2.9-Linux/lib64/libexpat.so
expat-2.2.9-Linux/lib64/libexpat.so.1
expat-2.2.9-Linux/lib64/libexpat.so.1.6.11
expat-2.2.9-Linux/lib64/pkgconfig/expat.pc
expat-2.2.9-Linux/share/doc/expat/AUTHORS
expat-2.2.9-Linux/share/doc/expat/changelog …
```

CMake: Support "make package" based on CPack

---

.travis.sh
expat/tests/minicheck.c

Context is ex-issue #382. @Oleksandr-Popovych any chance you could do review by 2020-10-31?
This pull request is inspired by https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-core/expat/expat/0001-Add-output-of-tests-result.patch

Make testrunner output more helpful (related to #382)

---

expat/tests/runtests.c

There is a small typo in expat/tests/runtests.c.
Should read `without` rather than `wtihout`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, wtihout -> without

---

expat/CMakeLists.txt

Otherwise flags specified in a CMake cross-compilation toolchain (such as
CMAKE_CXX_FLAGS_INIT) will not be added. This could also affect native
builds but is much more likely to be noticed when cross-compiling due to
missing essential flags.

CMake: Only set CMAKE_CXX_FLAGS after enable_language(CXX)

---

expat/Changes
expat/configure.ac

Addressed:
- warning: The macro `AC_CONFIG_HEADER` is obsolete.
Not addressed yet:
- warning: `AC_PROG_CC_C99` is obsolete; use `AC_PROG_CC`

configure.ac: Apply partial autoupdate-2.71

---

expat/CMakeLists.txt
expat/Changes

CMake: Support absolute paths for CMAKE_INSTALL_(LIB|INCLUDE)DIR (fixes #458)

---

expat/doc/reference.html

This fix makes no visible difference but stops static code analysers
from yielding warnings about not allowed ul inside paragraph.
Fix #464

Fix doc/reference.html badly inserted ul tag (fixes #464)

---

.github/workflows/coverage.yml

Sample case at https://github.com/libexpat/libexpat/runs/2647710794?check_suite_focus=true#step:5:37

GitHub Actions: Avoid error "would clobber existing tag" when triggered by pushing a new Git tag

---

expat/doc/reference.html

Allocating zero bytes with XML_GetBuffers may return NULL or a non-NULL
pointer depending on the current internal buffer state (#502).
Document this behavior, as it can be surprising.

doc/reference.html: Document that XML_GetBuffer(parser, 0) may return NULL

---

expat/CMakeLists.txt
expat/Changes

This fixes a post-2.4.1 regression from commit 3486fd6e3d2bc269660cedd3befa1ae649d1dcf4 introduced by pull request #495.

CMake: Ensure libexpat*.lib filenames with MSVC

---

expat/Changes
expat/lib/xmltok_ns.c

Symptom was:
```
In file included from xmltok.c:58:
xmltok_ns.c: In function ‘findEncodingNS’:
xmltok.h:276:10: warning: ‘buf’ may be used uninitialized [-Wmaybe-uninitialized]
276 |   (((enc)->utf8Convert)(enc, fromP, fromLim, toP, toLim))
|   ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
xmltok_ns.c:99:3: note: in expansion of macro ‘XmlUtf8Convert’
99 |   XmlUtf8Convert(enc, &ptr, end, &p, p + ENCODING_MAX - 1);
|   ^~~~~~~~~~~~~~
xmltok.h:276:10: note: by argument 5 of type ‘const char *’ to ‘enum XML_Convert_Result(const ENCODING *, const char **, const char *, char **, const char *)’ {aka ‘enum XML_Convert_Result(const struct encoding *, const char **, const char *, char **, const char *)’}
276 |   (((enc)->utf8Convert)(enc, fromP, fromLim, toP, toLim))
| …
```

lib: Address GCC 11.2.1 compiler warning

---

expat/CMakeLists.txt
expat/Changes
expat/expat.pc.cmake

Error from CMake 3.7.2 was:
```
CMake Error at CMakeLists.txt:482 (file):
file Incorrect arguments to GENERATE subcommand.
```

CMake: Make call to file(GENERATE [..]) work for CMake <3.19

---

expat/Changes
expat/lib/xmlparse.c

[CVE-2021-45960] lib: Detect and prevent troublesome left shifts in function storeAtts (fixes #531)

---

expat/Changes
expat/run.sh.in

Inspired by https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-expat/002-fix-tests.patch.
CC @1480c1 @JPeterMugaas

run.sh.in: Do not use Wine with Cygwin and MSYS2

---

expat/Changes
expat/lib/xmlparse.c

[CVE-2021-46143] lib: Prevent integer overflow on m_groupSize in function doProlog (fixes #532)

---

expat/Changes
expat/lib/xmlparse.c
expat/tests/runtests.c

[CVE-2022-23852] Prevent XML_GetBuffer signed integer overflow

---

expat/Changes
expat/xmlwf/xmlwf.c

Fixes issue #544 
Related to pull request #439
CC @hwt0415 @timbray

[>=2.3.0] xmlwf: Fix a memory leak on output file opening error (fixes #544)

---

expat/Changes
expat/lib/xmlparse.c

The related code has been introduced by commit cb8a4c756d057b948c1b41e7185dd69ef3ade3fb about 20 years ago.
A CVE has been requested from Mitre just now.
CC @rillig

[CVE-2022-23990] lib: Prevent integer overflow in function doProlog

---

expat/lib/xmlparse.c

Hello,
I've attempted to build the library but the Intel compiler complains:
```
xmlparse.c(7425): error: a value of type "void *" cannot be assigned to an entity of type "XML_Char={char} *"
result = memsuite->malloc_fcn(charsRequired * sizeof(XML_Char));
```
This is the only occurrence where memory is not cast to the target type. So it seems reasonable to ensure this doesn't result in errors in some environments.
Thanks

Stop casting void* results from calls to .malloc_fcn

---

expat/lib/xmlparse.c

It is possible to trigger stack exhaustion in build_model function if
depth of nested children in DTD element is large enough. This happens
because build_node is a recursively called function within build_model.
The code has been adjusted to run iteratively. It uses the already
allocated heap space as temporary stack (growing from top to bottom).
Output is identical to recursive version. No new fields in data
structures were added, i.e. it keeps full API and ABI compatibility.
Instead the numchildren variable is used to temporarily keep the
index of items (uint vs int).
Documentation and readability improvements kindly added by Sebastian.
Proof of Concept:
1. Compile poc binary which parses XML file line by line
```
cat > poc.c << EOF
#include <err.h>
#include <expat.h>
#include <stdio.h> …
```

[CVE-2022-25313] lib: Prevent stack exhaustion in build_model

---

expat/lib/xmlparse.c

It is possible to use an integer overflow in storeRawNames for out of
boundary heap writes. Default configuration is affected. If compiled
with XML_UNICODE then the attack does not work. Compiling with
-fsanitize=address confirms the following proof of concept.
The problem can be exploited by abusing the m_buffer expansion logic.
Even though the initial size of m_buffer is a power of two, eventually
it can end up a little bit lower, thus allowing allocations very close
to INT_MAX (since INT_MAX/2 can be surpassed). This means that tag
names can be parsed which are almost INT_MAX in size.
Unfortunately (from an attacker point of view) INT_MAX/2 is also a
limitation in string pools. Having a tag name of INT_MAX/2 characters
or more is not possible.
Expat can convert between different …

[CVE-2022-25315] lib: Prevent integer overflow in storeRawNames

---

expat/Changes
expat/lib/xmlparse.c
expat/tests/runtests.c

The iterative approach in build_model failed to fill children arrays
correctly. A preorder traversal is not required and turned out to be the
culprit. Use an easier algorithm.

Fix build_model regression

---

expat/Changes
expat/tests/runtests.c

tests: Resolve use of macros NAN and INFINITY for GNU G++ 4.8.2 (fixes #569)

---

expat/lib/expat.h

This has already been corrected in the official API reference docs

doc: Fix documentation of XML_EndDoctypeDeclHandler in <expat.h>

---

expat/Changes
expat/doc/reference.html
expat/lib/expat.h
expat/lib/xmlparse.c
expat/tests/runtests.c

lib: Relax fix to CVE-2022-25236 with regard to RFC 3986 URI characters (fixes #572)

---

expat/Changes
expat/lib/xmlparse.c

```
expat/lib/xmlparse.c:4288:21: error: Uninitialized variable: &versionend [uninitvar]
&version, &versionend, &encodingName, &newEncoding, &standalone)) {
^
```

lib: Address Cppcheck 2.8.1 warning / fix CI

---

expat/CMakeLists.txt

This fixes unwanted side effects when libexpat is used with FetchContent
in another cmake-based project. Setting CMAKE_*_POSTFIX affects the
whole project, while here we only want to define the postfix for libexpat
itself.

CMake: Set target properties *_POSTFIX instead of global vars CMAKE_*_POSTFIX

---

expat/lib/libexpat.def
expat/lib/libexpatw.def

MinGW expects a populated LIBRARY field. Alternatively it can just be
removed.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

Fix .def files syntax for MinGW

---

expat/fuzz/.gitignore

issue-630: libexpat/expat/fuzz/.gitignore changed to not ignore alredy-committed source

File expat/fuzz/.gitignore changed to not ignore already-committed source files (fixes #630)

---

expat/coverage.sh

Observed paths include:
- `/usr/share/mingw-w64/include` (on Ubuntu)
- `/usr/i686-w64-mingw32/usr/include` (on Gentoo)

coverage.sh: Exclude MinGW headers

---

expat/apply-clang-format.sh

Found with shellcheck:
SC2185: Some finds don't have a default path. Specify '.' explicitly.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

apply-clang-format.sh: Add support for BSD find

---

expat/apply-clang-format.sh
expat/expat_config.h.cmake

meson has a bug where #cmakedefine with leading whitespace is not transformed.
For consistency, remove whitespace from the second define.

CMake: Drop leading whitespace from a #cmakedefine line in file expat_config.h.cmake to workaround issues with Meson

---

expat/lib/xmlparse.c

It is possible to concoct a situation in which parsing is suspended while substituting in an internal entity, so that `XML_ResumeParser` directly uses `internalEntityProcessor` as its processor.  If the subsequent parse includes some unclosed tags, this will return without calling `storeRawNames` to ensure that the raw versions of the tag names are stored in memory other
than the parse buffer itself.  If the parse buffer is then changed or reallocated (for example if processing a file line by line), badness will ensue.
This patch ensures `storeRawNames` is always called when needed after calling `doContent`.  The earlier call to `doContent` does not need the same protection; it only deals with entity substitution, which cannot leave unbalanced tags, and in any case the raw names will be …

Ensure raw tagnames are safe exiting internalEntityParser

---

expat/Changes
expat/tests/runtests.c

Follow-up to PR #629 (which contains the fix)

[CVE-2022-40674] tests: Cover heap use-after-free issue in doContent (follow-up to #629)

---

expat/Changes
expat/tests/runtests.c

Symptom:
```
../../../tests/runtests.c:4994:1: warning: no previous prototype for ‘suspending_comment_handler’ [-Wmissing-prototypes]
4994 | suspending_comment_handler(void *userData, const XML_Char *data) {
| ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

tests: Address GCC warning -Wmissing-prototypes

---

expat/CMakeLists.txt

`CMAKE_*_POSTFIX` was changed to `EXPAT_*_POSTFIX` in https://github.com/libexpat/libexpat/pull/608. As a result, debug pkgconfig file was not correct.

[2.4.9] CMake: Fix generation of pkgconfig file

---

expat/CMakeLists.txt

When building static library with mingw the output file name should be `libexpat.a`, not `libexpat-1.dll`.
This is a regression from https://github.com/libexpat/libexpat/pull/624, reported in https://github.com/microsoft/vcpkg/issues/27132.

[2.4.9] CMake: Fix static library name when building with MinGW

---

expat/Changes
expat/lib/xmlparse.c
expat/tests/runtests.c

Fixes #652
Alternative patch + reproducer test case

Stop leaking tag bindings (fixes #652)

---

expat/Changes
expat/lib/xmlparse.c
expat/tests/runtests.c

Fixes #649
Alternative patch + reproducer test case

[CVE-2022-43680] Fix overeager DTD destruction (fixes #649)

---

expat/lib/siphash.h
expat/lib/xmlparse.c
expat/lib/xmltok.c
expat/tests/chardata.c
expat/tests/memcheck.c
expat/tests/runtests.c
expat/tests/structdata.c
expat/xmlwf/readfilemap.c
expat/xmlwf/xmlwf.c

I'm really not familiar with the codebase, so please review carefully.  libexpat is a dependency of a dependency of a dependency for me, and I'm just trying to get everything building with more warnings fixed.
The `_GNU_SOURCE` thing in particular could maybe be addressed differently.  Perhaps it doesn't need to be defined at all?

Fix miscellaneous Clang and Cppcheck 2.9 style warnings

---

expat/lib/xmlparse.c

Reformulated strtoul() error checking.
This also fixed a clang -Wcast-qual warning.

Fix getDebugLevel handling of empty environment variable value

---

expat/ConfigureChecks.cmake
expat/expat_config.h.cmake

Because of a bug in meson, defines need to be the same case.
Signed-off-by: Rosen Penev <rosenp@gmail.com>

CMake: Lowercase off_t and size_t

---

expat/CMakeLists.txt
expat/Changes
expat/examples/Makefile.am
expat/examples/element_declarations.c

Here is an example XML document to feed into the new example C code:
```xml
<!DOCTYPE demo [
<!ELEMENT empty1 EMPTY>
<!ELEMENT any2 ANY>
<!ELEMENT mixed31 (#PCDATA)>
<!ELEMENT mixed32 (#PCDATA|name41|name42)*>
<!ELEMENT choice5 (name43|name44)*>
<!ELEMENT seq61 (name45)+>
<!ELEMENT seq62 (name46, name47)*>
<!ELEMENT seq63 ((name48+)*)?>
]>
<demo/>
```

examples: Add new example on element declarations

---

.github/workflows/coverage.yml

.. because image `ubuntu-22.04` just stopped adding repository `ppa:ondrej/php`. Related commit: https://github.com/actions/runner-images/commit/cc71c8b504a5efec7d25054a016dbe7f34553df4

Fix CI / coverage.yml: Drop ppa:ondrej/php removal

---

.github/workflows/linux.yml

Symptom was:
> /usr/bin/ld: cannot find /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.asan_static-x86_64.a: No such file or directory
> /usr/bin/ld: cannot find /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.asan-x86_64.a: No such file or directory
Related:
https://github.com/llvm/llvm-project/issues/60008

Fix Linux CI / Make sure that AddressSanitizer Clang files are always available

---

expat/lib/xmlparse.c

AFAIU, without parentheses wrapping these zeros, some compilers emit disabled-code-warnings, suggesting to "silence by adding parentheses to mark code as explicitly dead". At least this is the case when building CPython, which makes use of `xmlparse.c`: 
```
gcc  -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include     -c ./Modules/cjkcodecs/_codecs_cn.c -o Modules/cjkcodecs/_codecs_cn.o
./Modules/expat/xmlparse.c:3116:9: warning: code will never be executed [-Wunreachable-code]
parser->m_characterDataHandler(parser->m_handlerArg, parser->m_dataBuf,
^~~~~~ …
```

Silence dead code warnings caused by if (0) and company

---

expat/coverage.sh

.. e.g. when someone forks the Git repository in a way that only copies the `master` branch but no tags.

coverage.sh: Be robust towards absence of Git tags

---

.github/workflows/autotools-cmake.yml
.github/workflows/cmake-required-version.yml
.github/workflows/coverage.yml
.github/workflows/cppcheck.yml
.github/workflows/expat_config_h.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/valid-xml.yml

Closes #693 
- expat_config_h.yml: success https://github.com/joycebrum/libexpat/actions/runs/4344532736
- cmake-required-version: success https://github.com/joycebrum/libexpat/actions/runs/4344532730
- autotools-cmake: success https://github.com/joycebrum/libexpat/actions/runs/4344532740
- valid-xml: success https://github.com/joycebrum/libexpat/actions/runs/4344532737
- cppcheck: success https://github.com/joycebrum/libexpat/actions/runs/4344532733
- linux: success https://github.com/joycebrum/libexpat/actions/runs/4344532739
- macos: success https://github.com/joycebrum/libexpat/actions/runs/4344532745
- coverage: error due to lack of access to travis https://github.com/joycebrum/libexpat/actions/runs/4344532726, but the reading permission seems to be enough

Actions: Set permissions to "contents: read" to avoid permissive workflows

---

expat/lib/winconfig.h

If it is already defined externally, do not define it again.

winconfig: Avoid redefinition of WIN32_LEAN_AND_MEAN

---

.github/workflows/autotools-cmake.yml
.github/workflows/cmake-required-version.yml
.github/workflows/coverage.yml
.github/workflows/cppcheck.yml
.github/workflows/expat_config_h.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/valid-xml.yml

For proof that GitHub Dependabot can still keep things up to date for us with the new format see https://github.com/gentoo-ev/www.gentoo-ev.org/pull/5/files .
CC @joycebrum

CI: Pin all GitHub Actions to specific commits for security

---

expat/lib/xmlparse.c

This is a variation of https://github.com/libexpat/libexpat/pull/714 that makes more sense.

debugLevel fields should be unsigned longs, not integers

---

expat/Changes
expat/cmake/autotools/expat.cmake
expat/tests/runtests.c

Error was:
```
expat/tests/runtests.c:6818:50: error: Uninitialized variable: &storage [uninitvar]
ParserPlusStorage parserPlusStorage = {parser, &storage};
^
```

runtests.c: Initialize storage prior to usage (cppcheck 2.11) + autotools: Sync CMake templates with CMake 3.25

---

expat/tests/handlers.h

Follow-up to #738
The file checks for `XML_DTD` being defined.

tests/handlers.h: Be explicit about direct dependency expat_config.h

---

expat/CMakeLists.txt

Related CMake output:
> ```
> CMake Deprecation Warning at CMakeLists.txt:37 (cmake_minimum_required):
>   Compatibility with CMake < 3.5 will be removed from a future version of
>   CMake.
>
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> ```

CMake: Require CMake >=3.5.0

---

expat/tests/basic_tests.c
expat/tests/common.c
expat/tests/common.h
expat/tests/handlers.c
expat/tests/handlers.h
expat/tests/minicheck.c
expat/tests/minicheck.h
expat/tests/runtests.c

Lots of tests use _XML_Parse_SINGLE_BYTES(), which parses the input one byte at a time. Repeating the tests with different chunk sizes (1,2,3,4,5) is a cheap way to get more test coverage.

Repeat tests with different SINGLE_BYTES chunk sizes

---

expat/tests/alloc_tests.c
expat/tests/handlers.c
expat/tests/runtests.c

...including one test that needed fixing to get it passing in these new conditions.

Run SINGLE_BYTES with no chunking, too

---

expat/lib/xmlparse.c
expat/lib/xmlrole.c
expat/lib/xmltok.c
expat/tests/chardata.c
expat/tests/runtests.c
expat/xmlwf/xmlfile.c
expat/xmlwf/xmlwf.c

.. and priorize the local build over the system header.

Make inclusion to expat_config.h consistent

---

expat/tests/memcheck.c

Symptom was this compile warning from MinGW GCC 12:
> ```
> [..]/expat/tests/memcheck.c: In function ‘tracking_realloc’:
> [..]/expat/tests/memcheck.c:169:25: error: pointer ‘ptr’ may be used after ‘realloc’ [-Werror=use-after-free]
>   169 |       entry->allocation = ptr;
>       |       ~~~~~~~~~~~~~~~~~~^~~~~
> [..]/expat/tests/memcheck.c:166:25: note: call to ‘realloc’ here
>   166 |     entry->allocation = realloc(ptr, size);
>       |                         ^~~~~~~~~~~~~~~~~~
> ```
The warning is a false positive since the code was only using `ptr` when `realloc` failed where it is documented that the original pointer is not freed.
The workaround is to no longer override-and-restore entry->allocation but to only write to it when `realloc` was successful.  The original value was …

tests/memcheck.c: Avoid false positive -Wuse-after-free

---

expat/tests/basic_tests.c
expat/tests/common.c
expat/tests/handlers.c
expat/tests/handlers.h
expat/tests/minicheck.c
expat/tests/minicheck.h

Naming [inspired by GoogleTest](https://github.com/google/googletest/blob/main/docs/reference/assertions.md#expect_true-expect_true).
CC @Snild-Sony

tests: Rename fail_unless to assert_true for clarity

---

expat/tests/acc_tests.c

The test makes use of general entities (not parameter entities) but was mis-filed under parameter entities.

tests/acc_tests.c: Move second BOM accounting test to the right place

---

expat/lib/xmlparse.c
expat/tests/misc_tests.c

xmlparse.c: Fix `NULL` pointer dereference in `setContext` via `XML_ExternalEntityParserCreate` for `XML_DTD` undefined

---

expat/tests/acc_tests.c
expat/tests/basic_tests.c
expat/tests/handlers.c
expat/tests/handlers.h

Since 091ba48d7a5a8fcb65ba383d81d062c6e9046a88, all tests are also run with chunkSize=0, which makes _XML_Parse_SINGLE_BYTES behave like XML_Parse.
Some tests were already using loops or conditions to switch between the two. This is no longer necessary.

tests: Stop switching between XML_Parse and _XML_Parse_SINGLE_BYTES

---

expat/tests/handlers.h

Follow-up to #783
Last use removed in commit b3d14b0d3c96700a81be06e7482d3735245611ca.
CC @Snild-Sony

tests/handlers.h: Drop unused type XmlParseFunction

---

expat/lib/xmlparse.c
expat/tests/basic_tests.c

Until now, the buffer size to grow to has been calculated based on the distance from the current parse position to the end of the buffer. This means that the size of any already-parsed data was not considered, leading to inconsistent buffer growth.
Growing the buffer based on its total size makes its growth consistent.
The commit includes a test that checks that we can reach the max buffer size (usually INT_MAX/2 + 1) regardless of previously parsed content.

Grow buffer based on current size

---

expat/tests/acc_tests.c

Follow-up to #750 in some sense.
Effectively reverts commit f6f5d9bb4cc05fb9544ec92e0c3e6a44013cbc1f of pull request #571.

tests: Use NAN and INFINITY of C99 and C++11

---

expat/tests/basic_tests.c

The tests added in #771 included a workaround for allocation failures in 32-bit mingw CI (which neither I nor @hartwork could reproduce locally).
Instead of applying it to all less-than-64-bit platforms, let's narrow the workaround to just the known failure: 32-bit mingw.

tests: Narrow test_buffer_can_grow_to_max mingw allocation workaround at compile time

---

expat/tests/alloc_tests.c
expat/tests/basic_tests.c
expat/tests/common.c
expat/tests/handlers.c
expat/tests/misc_tests.c
expat/tests/ns_tests.c

Follow up to #755 in some sense
CC @Snild-Sony

tests: Migrate more tests to variable chunk size parsing

---

expat/fuzz/xml_parse_fuzzer.c
expat/fuzz/xml_parsebuffer_fuzzer.c

Using other parsers comes from https://introspector.oss-fuzz.com/project-profile?project=expat
Another way to achieve so would be to create multiple targets based on the parser
No bugs found in a few minutes from oss-fuzz public corpus, but coverage grows and reaches functions like `doIgnoreSection`

fuzz: improve coverage

---

expat/fuzz/xml_parse_fuzzer.c
expat/fuzz/xml_parsebuffer_fuzzer.c

@hartwork what do you think about this to make `internalEntityProcessor` reachable by fuzzing ?
If it looks good, I will put it in xml_parsebuffer_fuzzer.c as well

fuzz: Improve coverage by maybe stopping the parser

---

expat/tests/basic_tests.c

Follow-up to #789
`CLOCKS_PER_SEC` turned out to be as small as 128 in practice on machine `cfarm240.cfarm.net`.
CC @Snild-Sony

tests: Fix `CLOCKS_PER_SEC` guard for arm64 FreeBSD reality

---

expat/expat.pc.cmake
expat/expat.pc.in

Alternative to #805
This affects the output of command `pkg-config --cflags --static expat`.

pkg-config: Add missing `-DXML_STATIC` for Windows (alternative to #805)

---

expat/lib/expat.h
expat/lib/internal.h

> In file included from ./../lib/internal.h:149,
>                  from codepage.c:38:
> ./../lib/expat.h:1045:5: warning: "XML_GE" is not defined, evaluates to 0 [-Wundef]
>  1045 | #if XML_GE == 1
>       |     ^~~~~~
> ./../lib/internal.h:158:5: warning: "XML_GE" is not defined, evaluates to 0 [-Wundef]
>   158 | #if XML_GE == 1
>       |     ^~~~~~

Fix compiler warnings

---

expat/lib/internal.h
expat/lib/xmlparse.c
expat/tests/basic_tests.c

Follow-up to #789, this PR replaces `clock()` in a test case with counting the number of scanned bytes instead. This will avoid the risk of timing-/performance-based flakiness, and avoid problems caused by low CLOCKS_PER_SEC on certain platforms.
The first patch replaces `g_parseAttempts` with `g_bytesScanned`. The second patch uses the new value to replace `clock()`.

tests: Replace clock counting with counting scanned bytes

---

expat/configure.ac
expat/doc/Makefile.am

Fixes #821
File `doc/xmlwf.1` should not be cleaned when building with `./configure --without-docbook`, and re-compilation of the file  hould take precedence over a pre-built copy where available.
Also, variable `CLEANFILES` can be used to simplify things a bit in `Makefile.am`.

Autotools: Re-work handling of xmlwf.1 (fixes #821)

---

expat/CMakeLists.txt
expat/apply-clang-tidy.sh
expat/lib/Makefile.am
expat/lib/internal.h
expat/lib/xmlparse.c
expat/tests/Makefile.am

Hide test-only code behind new (internal) macro `XML_TESTING` (alternative to #826)

---

expat/configure.ac

Follow-up to #490 in some sense

`configure.ac`: Protect against `expat_config.h.in` defining `SIZEOF_VOID_P`

---

expat/doc/reference.html
expat/lib/expat.h

Fixes #828
Regression from 2.6.0 commit caa27198637683b15d810737bb8a6a81af19bfa5.

Expose billion laughs API with `XML_DTD` without `XML_GE` (fixes #828)

---

expat/lib/xmlparse.c
expat/tests/acc_tests.c

Part of #839
CC (in alphabetic order) @catenacyber @RMJ10 @Snild-Sony

Prevent billion laughs attacks in isolated external parser (part of #839)

---

expat/doc/Makefile.am

Not using quotes causes problems when DOCBOOK_TO_MAN contains command and argument

[2.6.1] Fix DOCBOOK_TO_MAN variable use in doc Makefile

---

.github/workflows/autotools-cmake.yml
.github/workflows/cmake-required-version.yml
.github/workflows/codespell.yml
.github/workflows/coverage.yml
.github/workflows/cppcheck.yml
.github/workflows/expat_config_h.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/valid-xml.yml

Some already had `workflow_dispatch` enabled.

Allow triggering GitHub Actions workflows manually

---

expat/Makefile.am
expat/README.md
expat/qa.sh

Running find without path is a GNU extension.  GNU find uses current directory as starting-point in this case.  Better always use an explicit . in build scripts to support find on other systems.

Always provide path to find(1) for portability

---

expat/ConfigureChecks.cmake
expat/configure.ac

As the [manual](https://linux.die.net/man/2/syscall) states, if you want to make a syscall then you need `#define _GNU_SOURCE`
Without that the `check_c_source_compiles` fails on a Fedora 40 system with
````
src.c:6:13: error: implicit declaration of function ‘syscall’ [-Wimplicit-function-declaration]
6 |             syscall(SYS_getrandom, NULL, 0, 0);
|             ^~~~~~~
````
when this check should pass, as `SYS_getrandom` is available, only the declaration of `syscall` is behind a chain of defines `_GNU_SOURCE` -> `_DEFAULT_SOURCE` -> `__USE_MISC`

Fix `check_c_source_compiles` of `HAVE_SYSCALL_GETRANDOM`

---

.github/workflows/coverage.yml

Was broken by https://github.com/actions/runner-images/issues/9679 .

`coverage.yml`: Fix for image `ubuntu-22.04` of `20240514.2.0`

---

expat/lib/xmlparse.c

As a part of the `ENTITY` struct, `is_param` is correctly initialized even when `XML_DTD` is not defined. This can be seen in the `lookup` function, which sets all the `ENTITY` memory, including the `is_param` flag, to zero during the `ENTITY` creation. Additionally, `is_param` can only be assigned `XML_TRUE` when `XML_DTD` is defined, which makes `XML_DTD` checks before `is_param` accesses not necessary.
Currently, some of the `is_param` accesses are guarded by the `XML_DTD` and some not. This commit removes all `XML_DTD` guards that are meant for `is_param` accesses.

Remove `XML_DTD` guards before `is_param` accesses

---

expat/doc/reference.html
expat/lib/xmlparse.c
expat/tests/basic_tests.c

[CVE-2024-45490] lib: Reject negative len for `XML_ParseBuffer` (fixes #887)

---

expat/lib/xmlparse.c

[CVE-2024-45491] lib: Detect integer overflow in `dtdCopy` (fixes #888)

---

expat/lib/xmlparse.c

[CVE-2024-45492] lib: Detect integer overflow in function `nextScaffoldPart` (fixes #889)

---

expat/examples/.gitignore

`.gitignore`: Add missing example `element_declarations`

---

expat/CMakeLists.txt

As the find module and the config create the expat::expat alias for expat, the build-process should do this also to make it easier to include this in a chainbuild

Add alias expat::expat

---

.github/workflows/linux.yml

There is no package `debsuryorg-archive-keyring` in Ubuntu focal, so it has to be excluded from the list of packages that are reverted back to Ubuntu focal.
Symptom was:
```console
debsuryorg-archive-keyring/focal libgd3:amd64/focal libhashkit2:amd64/focal \
libmemcached11:amd64/focal libpcre2-16-0:amd64/focal libpcre2-32-0:amd64/focal \
libpcre2-8-0:amd64/focal
Reading package lists...
Building dependency tree...
Reading state information...
E: Release 'focal' for 'debsuryorg-archive-keyring' was not found
```
Same as https://github.com/uriparser/uriparser/pull/199 .

Fix CI / `linux.yml`: Fix mishandling of package `debsuryorg-archive-keyring`

---

expat/examples/element_declarations.c
expat/lib/xmlparse.c
expat/xmlwf/xmlfile.c

Format strings used %d to print variables with unsigned values. Changing to %u to match signedness.
Fixes "clang -Wformat-signedness" warnings.

Fix signedness of format strings

---

expat/doc/reference.html

doc: Add missing documentation of error `XML_ERROR_NOT_STARTED` (follow-up to #915)

---

.github/workflows/autotools-cmake.yml
expat/cmake/autotools/expat-noconfig__macos.cmake.in

.. to match what Autotools is producing in reality at build time. Unlike CMake, Autotools does not produce file `libexpat.@SO_MAJOR@.@SO_MINOR@.@SO_PATCH@.dylib` when compiling on macOS.
What the commit does on the CI side is closely mimicking a similar thing with MinGW that existed until 7731dd5b90621a9e4696d1c467bca2b6ece6e3e6^ .
Fixes #935

Make Autotools-generated CMake files look for `libexpat.@SO_MAJOR@.dylib` (fixes #935)

---

expat/coverage.sh

.. to suppress output "no messages were reported".

`coverage.sh`: Pass `-q -q` for LCOV >=2.1

---

expat/CMakeLists.txt
expat/README.md

Symptom was:
```
CMake Deprecation Warning at CMakeLists.txt:37 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```

Drop support for CMake <3.10

---

expat/CMakeLists.txt

fuzzers|cmake: Check for availability of protobuf compiler

---

.github/workflows/fuzzing.yml
expat/CMakeLists.txt

Follow-up to #950
This reverts commit d7e41e2de81768122df9fab9fe8c57bf91652f77.

fuzzers|cmake: Stop linking `xml_lpm_fuzzer` against Abseil, explicitly

---

expat/CMakeLists.txt

ONLY gcc has `-Wno-pedantic-ms-format`:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wno-pedantic-ms-format
```logs
[root@wlbvm-deb 2025-02-07 15:44:40 +0800 nativepkgs]% CROSS_TOOLCHAIN_ROOT="$PWD/toolchain/llvm-mingw" ./build_win-mingw_aarch64.sh libexpat shared
cmake -S "/root/code/nativepkgs/deps/libexpat/expat" -B "/root/code/nativepkgs/tmp/libexpat/win-mingw/aarch64"   -D CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON     -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON   -D CMAKE_INSTALL_PREFIX="/root/code/nativepkgs/out/libexpat/win-mingw/aarch64"    -D CMAKE_INSTALL_LIBDIR:PATH=lib     -D EXPAT_WARNINGS_AS_ERRORS:BOOL=1   -D EXPAT_BUILD_TOOLS:BOOL=0      -D EXPAT_BUILD_EXAMPLES:BOOL=0   -D EXPAT_BUILD_TESTS:BOOL=0      -D EXPAT_BUILD_DOCS:BOOL=0       -D …
```

Fix warning: no `-Wno-pedantic-ms-format` (`-Wunknown-warning-option`) for LLVM MinGW

---

expat/CMakeLists.txt

.. to give OSS-Fuzz a chance at a successful build while their images are based on Ubuntu 20.04 with too-old Protobuf
Follow-up to #950
CC https://github.com/google/oss-fuzz/issues/13016

fuzzers|cmake: Disable `xml_lpm_fuzzer` for `-DEXPAT_OSSFUZZ_BUILD=ON`

---

expat/CMakeLists.txt

Follow-up to #955
Made possible by:
- https://github.com/google/libprotobuf-mutator/pull/263
- https://github.com/google/libprotobuf-mutator/pull/270
- https://github.com/google/libprotobuf-mutator/pull/274
- https://github.com/google/oss-fuzz/pull/13015

fuzzers|cmake: Re-enable `xml_lpm_fuzzer` for `-DEXPAT_OSSFUZZ_BUILD=ON`

---

expat/CMakeLists.txt

Because libprotobuf-mutator with tests enabled [already needs CMake >=3.13 in practice](https://github.com/google/libprotobuf-mutator/pull/276).
PS: Near-end-of-life Ubuntu "focal" 20.04 LTS has [CMake 3.16.3](https://packages.ubuntu.com/focal/cmake) and Debian "bullseye" old(!)stable has [CMake 3.18.4](https://packages.debian.org/bullseye/cmake).

Drop support for CMake <3.13

---

expat/fuzz/xml_parse_fuzzer.c
expat/fuzz/xml_parsebuffer_fuzzer.c
expat/qa.sh
expat/tests/xmltest.sh

This updates a few http links to their https version.
In one case, I made an additional change. In xmltest.sh, the URL ended with a dot, which was part of the sentence. I found that not ideal and changed it so there's a : before and the url itself is no longer part of the sentence.

Update links in code comments to HTTPS

---

.github/workflows/valid-xml.yml

We cannot keep [restarting CI three times](https://github.com/libexpat/libexpat/actions/runs/13712349520) just because the machine serving the Docbook DTD for OASIS Open has a bad day or two…

`valid-xml.yml`: Stop `xmllint` from loading DTD from the internet to address flaky CI

---

expat/tests/benchmark/benchmark.c

From `man fdopen`:
> The file descriptor is not dup'ed, and will be closed when the stream created by fdopen() is closed.
In reaction to https://github.com/libexpat/libexpat/pull/959/files#r1994451271
CC @Smattr

`tests/benchmark`: Resolve mistaken double close

---

expat/Changes
expat/apply-clang-tidy.sh

In reaction to https://github.com/llvm/llvm-project/issues/40656#issuecomment-2561999174
Thanks to @vszakats

Re-enable clang-tidy warning `clang-analyzer-valist.Uninitialized`

---

expat/Changes
expat/apply-clang-tidy.sh
expat/fuzz/xml_parse_fuzzer.c
expat/fuzz/xml_parsebuffer_fuzzer.c
expat/lib/xmlparse.c
expat/tests/alloc_tests.c
expat/tests/basic_tests.c
expat/tests/handlers.c
expat/tests/misc_tests.c
expat/tests/nsalloc_tests.c
expat/xmlwf/unixfilemap.c
expat/xmlwf/xmlfile.c
expat/xmlwf/xmlwf.c

- All `bugprone-narrowing-conversions` warnings
- All `bugprone-suspicious-string-compare` warnings
- Some `google-readability-casting` warnings

Address more clang-tidy warnings

---

expat/Changes
expat/apply-clang-tidy.sh
expat/lib/xmlparse.c

Address clang-tidy warning `misc-no-recursion`

---

.github/workflows/windows-binaries.yml
expat/CMakeLists.txt

CMake: Drop support for CMake <3.15 + fix `-DEXPAT_MSVC_STATIC_CRT=ON` (alternative to #1006)

---

expat/Changes
expat/lib/xmlparse.c

Follow-up to #1034, started out at https://github.com/libexpat/libexpat/pull/1034/files#r2353901428
---
Matthew Fernandez (@Smattr) and I teamed up on whether function `expat_realloc` could be vulnerable to integer overflow in line:
```
mallocedPtr = parser->m_mem.realloc_fcn(mallocedPtr, sizeof(size_t) + size);
^
```
We ended up with a mathematical proof that, fortunately, the current code already is safe from overflow.
The proof uses technique "proof by contradiction". Let's assume, there *was* a risk of integer overflow. For a risk of overflow, these four conditions would all need to be met, together:
```
(1) `SIZE_MAX < sizeof(size_t) + size`
or we would not hit an overflow on `size_t`.
(2) `size > prevSize`
or `expat_malloc` would have already not allocated earlier
as `expat_realloc` …
```

Document safe-from-overflow proof (follow-up to #1034)

---

expat/Changes
expat/lib/internal.h
expat/lib/xmlparse.c
expat/tests/alloc_tests.c

Fixes #1046, follow-up to #1034
CC @DerDakon @Smattr

Fix alignment of internal allocations for some non-amd64 architectures (e.g. sparc32) (fixes #1046)

---

expat/xmlwf/xmlfile.c

In reaction to https://github.com/python/cpython/pull/139234#discussion_r2369500837
These functions no longer exist and calling them only worked because of these alias macros:
```console
$ git grep XML_GetError | grep -v XML_GetErrorCode
lib/expat.h:#  define XML_GetErrorLineNumber XML_GetCurrentLineNumber
lib/expat.h:#  define XML_GetErrorColumnNumber XML_GetCurrentColumnNumber
lib/expat.h:#  define XML_GetErrorByteIndex XML_GetCurrentByteIndex
```
CC @picnixz

`xmlwf`: Resolve use of functions `XML_GetErrorLineNumber` and `XML_GetErrorColumnNumber`

---

expat/lib/xmlparse.c
expat/tests/misc_tests.c

According to the XML standard, tags must be closed within the same element in which they are opened. Since the change of the entity processing method in version 2.7.0, violations of this rule have not been handled correctly for entities.
This PR adds the required checks to detect any violations and restores the correct behaviour.

Fix detection of asynchronous tags in entities

---

expat/lib/xmlparse.c

The source expression, `bytesToAllocate`, is a `size_t` and the type of the corresponding parameter in the function it is being passed to is also `size_t`. Thus this cast is redundant.
Note that this cast was not losing information. On platforms like x86-64, `sizeof(unsigned) < sizeof(size_t)`. But `bytesToAllocate` is the result of a call to `poolBytesToAllocateFor` here that can never return a value that would overflow an `unsigned`.
The source of this seems to have been an oversight in 810b74e4703dcfdd8f404e3cb177d44684775143.

lib: Remove cast that truncates a `size_t` to an `unsigned`

---

expat/lib/xmlparse.c

Some tweaks spawned from the review of https://github.com/libexpat/libexpat/pull/1072.

Improve determination of buffer size `bufSize` in function `doContent`
