libexpat/libexpat

expat/Changes, expat/lib/xmlparse.c
Meant to address issue #25.
@pascal-cuoq, if you have a minute review would be very welcome.
=> Detect integer overflows in function poolGrow (issue #25)

expat/Changes, expat/Makefile.in, expat/xmlwf/filemap.h, expat/xmlwf/readfilemap.c, expat/xmlwf/unixfilemap.c, expat/xmlwf/win32filemap.c, expat/xmlwf/xmlfile.c
Meant to address issue #28. Review welcome.
=> Do not mmap files bigger than INT_MAX / 2 + 1

expat/lib/xmlparse.c
Candidate for a fix to issue #31
=> Fix sharing of hash salt across parsers

expat/coverage.sh
@RMJ10 I don't have `libwinpthread-1.dll` locally but I could imagine this fixes things for you. Could you give it a try?
=> coverage.sh: Symlink libwinpthread-1.dll as well for Linux Mint

expat/Makefile.in
For MinGW cross-compilation, second try.
=> Makefile.in: Waterproof against differences in line endings

expat/Changes, expat/lib/xmlparse.c
Candidate for mid/long-term fix to #91 (and successor to #90). Review wanted.
@smcv @cometzero
=> Nonblock fail getrandom

expat/CMakeLists.txt, expat/Changes, expat/MANIFEST, expat/Makefile.in, expat/lib/expat.vcxproj, expat/lib/expat.vcxproj.filters, expat/lib/expat_static.vcxproj, expat/lib/expat_static.vcxproj.filters, expat/lib/expatw.vcxproj, expat/lib/expatw.vcxproj.filters, expat/lib/expatw_static.vcxproj, expat/lib/expatw_static.vcxproj.filters, expat/lib/loadlibrary.c, expat/lib/xmlparse.c
Candidate for #82.
@vszakats review welcome
=> Use `Curl_load_library` to fix DLL hijacking vulnerability

expat/conftools/ac_c_bigendian_cross.m4, expat/lib/xmltok_impl.c
=> Misc. typos

expat/Changes, expat/conftools/expatcfg-compiler-supports-visibility.m4
=> m4: Fix check for -fvisibility=hidden for Clang (fixes  #245)

expat/README.md
To see a preview check out https://github.com/luzpaz/libexpat/tree/README-repology
=> README: Add Repology badge showing repos package is available in

expat/lib/xmlparse.c
Alternative to pull request #269
Related issue: #268
CC @MohammedKhajapasha
=> Address variable shadowing (#268)

.travis.sh, .travis.yml, expat/Makefile.am, expat/qa.sh
=> Rewrite qa.sh (as a new base to #275)

.travis.sh, .travis.yml
Enable CI to cover XML_ATTR_INFO feature.
Signed-off-by: Mohammed Khajapasha <mohammed.khajapasha@intel.com>
=> Make CI cover both with and without XML_ATTR_INFO

.travis.sh, expat/qa.sh
@yevgenypats @catenacyber this is what I have in mind for a base to #292 to fix up upon #281. What do you think?
CC @MohammedKhajapasha
=> Fix qa.sh integration

.travis.yml, expat/Makefile.am, expat/fix-xmltest-log.sh, expat/qa.sh
=> [W.I.P.] Make Travis CI cover MinGW (#266)

expat/Changes, expat/lib/xmlparse.c, expat/tests/runtests.c
Aims at fixing #240
@pointsman @RMJ10 review welcome!
=> Fix stopping parser from inside end element handler (#240)

expat/configure-ac-style.md
#306
Live preview at https://github.com/libexpat/libexpat/blob/issue-306-configure-ac-style-doc/expat/configure-ac-style.md
@kkkunche have a minute for review?
=> configure-ac-style.md: Add configure.ac style guide (#306)

expat/lib/xmltok.c
=> xmltok.c: Fix unused variables warnings for -DXML_MIN_SIZE (for #331)

.travis.sh, .travis.yml, appveyor.yml, expat/CMakeLists.txt, expat/Changes, expat/Makefile.am, expat/cmake/mingw-toolchain.cmake, expat/expat_config.h.cmake, expat/qa.sh, expat/win32/expat.iss
=> Go further with CMake migration (for #330)

expat/CMakeLists.txt
=> CMake: Build fuzzing Expat once, not twelve times

.travis.yml, expat/lib/xmlparse.c, expat/lib/xmlrole.c, expat/qa.sh, expat/tests/runtests.c
=> Cover more build flags (fixes #324)

.travis.sh, .travis.yml, expat/coverage.sh, expat/xmlwf/codepage.c
=> Migrate coverage.sh from GNU Autotools to CMake (part of #330)

.travis.yml, expat/CMakeLists.txt
=> CMake: Fix approach to set(.. PARENT_SCOPE) (follow-up to #381)

expat/lib/xmlparse.c
=> Be more correct about const correctness on the inside

appveyor.yml
=> AppVeyor: Cover Visual Studio 16 2019 (related to #418)

appveyor.yml, expat/Changes, expat/README.md, expat/lib/siphash.h, expat/lib/xmlparse.c, expat/lib/xmltok.c, expat/tests/runtests.c, expat/win32/README.txt
=> Drop support for old versions of Visual Studio (fixes #422)

expat/CMakeLists.txt
Fixes #454
Related to #422, #426, #447
Review welcome, thanks in advance! :pray: 
CC @tbeu @SpaceIm
=> CMake: Be less rejective towards unsupported MSVC compilers for Conan (#454)

expat/CMakeLists.txt, expat/configure.ac, expat/lib/winconfig.h, expat/lib/xmlparse.c, expat/lib/xmlrole.c, expat/lib/xmltok.c, expat/tests/chardata.c, expat/tests/runtests.c, expat/tests/structdata.c, expat/xmlwf/xmlfile.c
PS: Merging will cause #466 need a rebase onto latest `master`.
=> Resolve macro HAVE_EXPAT_CONFIG_H

expat/Changes, expat/lib/xmltok.c, expat/lib/xmltok_impl.c, expat/tests/runtests.c
=> [XML_MIN_SIZE only] Fix segfault with UTF-16 CDATA (fixes #332)

.github/workflows/coverage.yml, .github/workflows/linux.yml
This reverts #476 (commit fe29a25ec008c610faf5fcf47cee3c48fe789ba3).
Related:
https://github.com/actions/virtual-environments/issues/3339
=> Actions: Drop/revert explicit addition of repository ppa:ondrej/php

expat/Changes, expat/lib/xmlparse.c, expat/tests/runtests.c
=> Fix accounting issues

expat/Changes, expat/doc/reference.html
=> [docs] Fix return value docs on XML_SetBillionLaughs[..] functions (fixes #522)

.github/workflows/linux.yml, expat/Changes, expat/lib/xmlparse.c
=> [CVE-2022-22822 to CVE-2022-22827] lib: Prevent more integer overflows

.github/workflows/cmake-required-version.yml, .github/workflows/linux.yml, expat/CMake.README, expat/CMakeLists.txt, expat/Changes, expat/README.md, expat/configure.ac, expat/coverage.sh, expat/doc/reference.html, expat/doc/xmlwf.xml, expat/lib/expat.h, expat/lib/xmlparse.c, expat/lib/xmltok_ns.c, expat/run.sh.in, expat/tests/runtests.c, expat/win32/expat.iss
=> Prepare release 2.4.3 (part of #533)

expat/CMakeLists.txt, expat/Changes
=> CMake: Enforce library versioning compatible with GNU Libtool for macOS (fixes #55)

expat/CMakeLists.txt, expat/Changes, expat/expat.pc.cmake, expat/expat.pc.in
Related to https://github.com/microsoft/vcpkg/pull/22575#issuecomment-1077707953
CC @dg0yt
=> Fix pkg-config files

.mailmap, COPYING, appveyor.yml, expat/COPYING, expat/lib/xmltok.c, expat/lib/xmltok_impl.c, expat/xmlwf/win32filemap.c, expat/xmlwf/xmlwf.c
=> Add /COPYING file + sync file headers (fixes #585)

.github/workflows/autotools-cmake.yml, expat/CMakeLists.txt, expat/Changes, expat/coverage.sh, expat/qa.sh
Fixes #622
@neheb @vtorri does this look right to you?
=> CMake: Produce libexpat-1.dll with MinGW in line with GNU Autotools (fixes #622)

expat/Changes, expat/fix-xmltest-log.sh
e.g. for https://github.com/libexpat/libexpat/runs/8053729230?check_suite_focus=true#step:5:554
=> fix-xmltest-log.sh: Drop more Wine bug output

expat/CMakeLists.txt, expat/Changes, expat/README.md
Related comment: https://github.com/libexpat/libexpat/issues/597#issuecomment-1097217985
=> CMake: Unify inconsistent use of set() and option() (related to #597)

expat/Changes, expat/lib/xmlparse.c, expat/tests/runtests.c
Fixes #612, variation of #615
CC @thejh @RMJ10
=> Fix corruption from undefined entities (fixes #612, variation of #615)

expat/Changes, expat/lib/xmlparse.c, expat/tests/runtests.c
=> Fix processing of nested entities (fixes #613)

expat/cmake/autotools/expat-config-version.cmake.in
=> autotools: Sync CMake templates with CMake 3.24

.github/workflows/coverage.yml
Fixes #720
Idea for the fix from https://github.com/actions/runner-images/issues/4589#issuecomment-1549465165, thanks to @ValdikSS :pray:
=> Fix CI (fixes #720)

expat/configure.ac
=> configure.ac: Support --disable-maintainer-mode (fixes #726)

expat/tests/basic_tests.c, expat/tests/chardata.c, expat/tests/handlers.c, expat/tests/handlers.h, expat/tests/minicheck.c, expat/tests/ns_tests.c, expat/tests/structdata.c
Follow-up to pull request #674.
This adds a mergability topping to target branch `pull-674-sandwich` to finish the sandwich around pull request #674 so that target branch `pull-674-sandwich` can be merged to `master`.
CC @RMJ10
=> Make branch `pull-674-sandwich` mergable to `master`

expat/CMakeLists.txt
=> CMake: Require a C99 compiler

.mailmap, expat/Changes, expat/lib/xmlparse.c, expat/lib/xmlrole.c, expat/lib/xmltok.c, expat/tests/acc_tests.c, expat/tests/acc_tests.h, expat/tests/alloc_tests.c, expat/tests/alloc_tests.h, expat/tests/basic_tests.c, expat/tests/basic_tests.h, expat/tests/common.c, expat/tests/common.h, expat/tests/dummy.c, expat/tests/dummy.h, expat/tests/handlers.c, expat/tests/handlers.h, expat/tests/misc_tests.c, expat/tests/misc_tests.h, expat/tests/ns_tests.c, expat/tests/ns_tests.h, expat/tests/nsalloc_tests.c, expat/tests/nsalloc_tests.h, expat/tests/runtests.c, expat/xmlwf/xmlfile.c
Hi, my English legal name was updated from "Dong-hee Na" to "Donghee Na"
There were several issues with my legal English name and I got approval from Korea government about updating it, 
so I would like to request updating my legal name in this repo too :)
Related story: https://x.com/dongheena92/status/1702490849282810223?s=20
=> Update legal name of Donghee Na

expat/tests/basic_tests.c
This is a continuation on https://github.com/libexpat/libexpat/pull/745
=> Add isFinal=XML_TRUE to more tests

expat/CMakeLists.txt, expat/tests/benchmark/benchmark.c
.. like the Autotools build system does.
=> CMake: Build `tests/benchmark/benchmark.c` for `EXPAT_BUILD_TESTS`

.github/workflows/fuzzing.yml, expat/fuzz/xml_parse_fuzzer.c, expat/fuzz/xml_parsebuffer_fuzzer.c
=> Make CI run fuzzing regression tests (fixes #367)

expat/lib/xmlparse.c, expat/tests/misc_tests.c
Fixes #812
Detailed analysis over at #812
CC @catenacyber @RMJ10 @Snild-Sony
=> Protect against closing entities out of order (fixes #812)

expat/lib/xmlparse.c
=> Get clang-format CI back in sync

expat/Changes
=> Add missing #821 #824 to 2.6.1 change log

expat/lib/xmlparse.c, expat/tests/basic_tests.c
Part of #839
CC (in alphabetic order) @catenacyber @RMJ10 @Snild-Sony @timbray
=> Reject direct parameter entity recursion (part of #839)

expat/lib/siphash.h
So that #871 has a chance at a green CI after rebase…
=> `lib/siphash.h`: Apply clang-format 18.1.5

expat/README.md
Documentation on the used Markdown extension:
- https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/
- https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
=> `README.md`: Promote call for help in the Changes file

expat/tests/misc_tests.c
Follow-up to pull request #318, related to issue #317
=> Improve tests for #317 (follow-up to #318)

expat/tests/handlers.c, expat/tests/handlers.h, expat/tests/misc_tests.c
Follow-up to pull request #318, related to issue #317
=> Tests: Cover doctype closing more

expat/Changes, expat/README.md
Related:
https://gcc.gnu.org/projects/cxx-status.html#cxx11
=> `README.md` and `Changes`: Document need for C++11 compiler for use from C++

.github/workflows/fuzzing.yml, expat/CMakeLists.txt, expat/README.md
Integrate a few smaller learnings from https://github.com/uriparser/uriparser/pull/209
=> Small fuzzing related improvements

expat/tests/benchmark/benchmark.c
https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use
=> `tests/benchmark`: Fix a harmless TOCTTOU + upfront refactorings + improve error messages

expat/Changes
=> Extend changelog (i.e. early bits of preparation for release 2.6.5)

.github/workflows/coverity-scan.yml, expat/Changes
=> Stop (trying to) upload to Coverity Scan from fork repositories

expat/CMakeLists.txt, expat/Changes
=> Leverage CMake >=3.13

.github/workflows/cppcheck.yml, .github/workflows/scripts/mass-cppcheck.sh, expat/Changes, expat/tests/benchmark/benchmark.c, expat/tests/minicheck.h, expat/tests/misc_tests.c
In reaction to https://github.com/libexpat/libexpat/actions/runs/13706980635/job/38344758335
=> Address Cppcheck warnings + fix Cppcheck CI

.github/workflows/fuzzing.yml, expat/Changes, expat/Makefile.am
=> Integrate missing fuzzer files with Automake (fixes #976)

.github/workflows/emscripten.yml, expat/Changes, expat/lib/internal.h
=> Fix `printf` format specifiers for 32bit Emscripten (fixes #983) + cover compilation with 32bit Emscripten in CI

expat/Changes, expat/lib/xmlparse.c
=> Address Frama-C warning

.github/workflows/clang-static-analyzer.yml, expat/Changes
- https://clang-analyzer.llvm.org/
- https://clang.llvm.org/docs/ClangStaticAnalyzer.html
=> Make GitHub Actions apply Clang Static Analyzer

expat/Changes, expat/README.md
=> `README.md`: Drop AppVeyor badge

expat/xmlwf/xmlwf_helpgen.py
Fix-up for commit 09fdf998e7cf3f8f9327e6602077791095aedd4d
=> xmlwf: Fix help generator (follow-up to #789)

expat/doc/reference.html
.. in documentation of function `XML_SetBillionLaughsAttackProtectionMaximumAmplification`
=> docs: Add missing `<p>..</p>` wrap

expat/Changes, expat/lib/xmlrole.h
=> Drop an OpenVMS support leftover (related to #14)

.github/workflows/fuzzing.yml, expat/qa.sh
In reaction to https://github.com/libexpat/libexpat/pull/1047#discussion_r2365688611
Follow-up to #1047
CC @thesamesam
=> Cleanup UBSan fatality (follow-up to #1047)
